spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    view:
      prefix: /
      suffix: .jsp


  datasource:
    url: jdbc:postgresql://localhost:5432/webpdm
    username: postgres
    password: postgres2023

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
#        hbm2ddl:
#          auto: update

webpdm:
  app:
    jwtSecret: ======================WEBPDM=Spring===========================
    jwtExpirationMs: 86400000
    jwtSessionAttribute: W88SBtkU3ScRKzBP6YUBx4Wg6kqpi5sCiqTLoKEyN

#management:
#  security:
#    enabled: false